mypoll/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polling.urls')),
]

polling/urls.py
from django.urls import path
from . import views

app_name = "polling"

urlpatterns = [
    path("",  views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(),  name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),


]

polling/models.py
import datetime
from django.utils import  timezone
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
    
    #was published recently
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

polling/views.py
from typing import Any
from django.db.models import F
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,  HttpResponseRedirect
from django.urls import reverse
from django.views import generic


from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'polling/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last ten published questions."""
        return Question.objects.order_by("-pub_date")[:10]

class DetailView(generic.DetailView):
    model = Question
    template_name = "polling/detail.html"

class ResultsView(generic.DetailView):
    model = Question
    template_name = "polling/results.html"

def vote(request, question_id):
    question =  get_object_or_404(Question, pk=question_id)
    try:
        selected_choice =  question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        #Redisplay the question voting form
        return render(
            request,
            "polling/detail.html",
            {
                "question": question, 
                "error_message": "You didn't select a choice."
             },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polling:results",  args=(question.id,)))

polling/templates/polling/detail.html
<form action="{% url 'polling:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
    <legend>
        <h1>{{ question.question_text }}</h1>
    </legend>
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>
    

polling/templates/polling/index.html
{% if latest_question_list %}
<ul>
{% for question in latest_question_list %}
<li><a href="{% url 'polling:detail' question.id %}">{{ question.question_text }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

polling/templates/polling/results.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
<a href="{% url 'polling:detail' question.id %}">Vote again?</a>